name: 'preview-apps'
on: # rebuild any PRs and main branch change
  pull_request:
  push:
    branches:
      - main

jobs:
  hasura-cloud-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Hasura Cloud Preview Apps
        uses: hasura/hasura-cloud-preview-apps@v0.1.5
        id: hasura_cloud_preview
        with:
          name: "article-author-prod${{github.env.GITHUB_HEAD_REF}}${{github.event.number}}"
          region: "ap-south-1"
          tier: "cloud_payg"
          hasuraProjectDirectoryPath: hasura
          hasuraEnv: |
            ENV_VAR_TEST=value_test
          postgresDBConfig: |
            POSTGRES_SERVER_CONNECTION_URI=${{secrets.PG_STRING}}
            PG_ENV_VARS_FOR_HASURA=HASURA_GRAPHQL_DATABASE_URL
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          HASURA_CLOUD_ACCESS_TOKEN: ${{secrets.HASURA_CLOUD_ACCESS_TOKEN_PROD}}

      - uses: hasura/comment-progress@v2.1.0
        if: ${{github.event.number != ''}}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          id: preview_app_comment
          number: ${{github.event.number}}
          repository: "wawhal/article-author"
          message: |
                  Console URL available at ${{steps.hasura_cloud_preview.outputs.consoleURL}}
                  GraphQL Endpoint available at ${{steps.hasura_cloud_preview.outputs.graphQLEndpoint}}
